kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "percona.fullname" . }}-config-files
  labels:
    app: {{ template "percona.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.configFiles | indent 2 }}
